# Generated by Django 5.1.5 on 2025-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(choices=[('Tata', 'Tata'), ('bmw', 'bmw'), ('Audi', 'Audi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fauil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(choices=[('petrol', 'petrol'), ('Desal', 'Desal'), ('CNG', 'CnG'), ('EV', 'EV')], max_length=50)),
                ('v_name', models.ManyToManyField(to='app.vehical')),
            ],
        ),
    ]
